jobs:
  - job: 'build_and_test_java'
    displayName: 'Build & Test'
    # Strategy for the job
    strategy:
      matrix:
        'java-17':
          image: 'Ubuntu-22.04'
          jdk_version: '17'
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: $(image)
    # Variables
    variables:
      MVN_CACHE_FOLDER: $(HOME)/.m2/repository
      MVN_ARGS: '-e -V -B'
    # Pipeline steps
    steps:
      # Get cached Maven repository
      - template: "../steps/maven_cache.yaml"
      - template: "../steps/prerequisites/install_yq.yaml"
      - template: '../steps/prerequisites/install_java.yaml'
        parameters:
          JDK_VERSION: $(jdk_version)
      # Build the Java code without tests
      - bash: "make java_install"
        displayName: "Build Java code"
        env:
          MVN_ARGS: "-DskipTests -e -V -B"
      - bash: "make spotbugs"
        displayName: "Run Spotbugs"
        env:
          MVN_ARGS: "-e -V -B"
      - bash: "make java_verify"
        displayName: "Build & Test Java"
        env:
          BUILD_REASON: $(Build.Reason)
          BRANCH: $(Build.SourceBranch)
          MVN_ARGS: "-e -V -B"
      - bash: "make release_files_check"
        displayName: "Check released files"
      - bash: ".azure/scripts/uncommitted-changes.sh"
        displayName: "Check for uncommitted files"
      # We have to TAR the target directory to maintain the permissions of
      # the files which would otherwise change when downloading the artifact
      - bash: tar -cvpf target.tar ./operator/target
        displayName: "Tar the target directory"
      - publish: $(System.DefaultWorkingDirectory)/target.tar
        artifact: Binary
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: JUnit
          testResultsFiles: '**/TEST-*.xml'
          testRunTitle: "Unit & Integration tests"
        condition: always()