jobs:
  - job: 'build_container'
    displayName: 'Build container'
    # Strategy for the job
    strategy:
      matrix:
        ${{ each arch in parameters.architectures }}:
          ${{ arch }}:
            arch: ${{ arch }}
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Base system
    pool:
      vmImage: 'Ubuntu-20.04'
    # Pipeline steps
    steps:
      # Install Prerequisites
      - template: "setup_docker.yaml"
      - template: "setup_yq.yaml"

      # Unpack the binary artifacts for container builds
      - task: DownloadPipelineArtifact@2
        inputs:
          source: '${{ parameters.artifactSource }}'
          artifact: Binary
          path: $(System.DefaultWorkingDirectory)/
          project: '${{ parameters.artifactProject }}'
          pipeline: '${{ parameters.artifactPipeline }}'
          runVersion: '${{ parameters.artifactRunVersion }}'
          runId: '${{ parameters.artifactRunId }}'
      - bash: tar -xvf target.tar
        displayName: "Untar the binaries"

      # Build and unload the containers
      - bash: "make docker_build docker_save"
        env:
          DOCKER_BUILDKIT: 1
          BUILD_REASON: $(Build.Reason)
          BRANCH: $(Build.SourceBranch)
          DOCKER_REGISTRY: "quay.io"
          DOCKER_ORG: "strimzi"
          DOCKER_ARCHITECTURE: $(arch)
        displayName: "Build containers - $(arch)"

      # We have to TAR the container archives directory and store it
      - bash: tar -cvpf containers-$(arch).tar ./docker-images/container-archives
        displayName: "Tar the containers"
      - publish: $(System.DefaultWorkingDirectory)/containers-$(arch).tar
        artifact: Containers-$(arch)