jobs:
  - job: 'deploy_java'
    displayName: 'Deploy Java'
    # Set timeout for jobs
    timeoutInMinutes: 60
    # Strategy for the job
    strategy:
      matrix:
        'java-17':
          image: 'Ubuntu-22.04'
          jdk_version: '17'
    # Base system
    pool:
      vmImage: $(image)
    # Pipeline steps
    steps:
      - template: "../steps/maven_cache.yaml"
      - template: '../steps/prerequisites/install_java.yaml'
        parameters:
          JDK_VERSION: $(jdk_version)
      - task: DownloadPipelineArtifact@2
        inputs:
          source: '${{ parameters.artifactSource }}'
          artifact: Binary
          path: $(System.DefaultWorkingDirectory)/
          project: '${{ parameters.artifactProject }}'
          pipeline: '${{ parameters.artifactPipeline }}'
          runVersion: '${{ parameters.artifactRunVersion }}'
          runId: '${{ parameters.artifactRunId }}'
      - bash: tar -xvf target.tar
        displayName: "Untar the target directory"
      - bash: "./.azure/scripts/push-to-central.sh"
        env:
          MVN_ARGS: "-e -V -B"
          BUILD_REASON: $(Build.Reason)
          BRANCH: $(Build.SourceBranch)
          GPG_PASSPHRASE: $(GPG_PASSPHRASE)
          GPG_SIGNING_KEY: $(GPG_SIGNING_KEY)
          CENTRAL_USERNAME: $(CENTRAL_USERNAME)
          CENTRAL_PASSWORD: $(CENTRAL_PASSWORD)
        displayName: "Deploy Java artifacts"