# Triggers
trigger:
  branches:
    include:
      - 'main'
      - 'release-*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

# Stages
stages:
  - stage: java_build
    displayName: Java build
    jobs:
      - template: 'templates/jobs/build_java.yaml'
