# Triggers
trigger:
  branches:
    include:
      - 'main'
      - 'release-*'
pr:
  autoCancel: true
  branches:
    include:
      - '*'

# Stages
stages:
  - stage: build_and_test_java
    displayName: Java build
    jobs:
      - template: 'templates/jobs/build_and_test_java.yaml'
  - stage: build_container
    displayName: Build Container
    dependsOn:
      - build_and_test_java
    jobs:
      - template: 'templates/jobs/build_container.yaml'
        parameters:
          artifactSource: 'current'
          artifactProject: 'strimzi'
          artifactPipeline: ''
          artifactRunVersion: ''
          artifactRunId: ''
          architectures: ['amd64']
