apiVersion: v2
appVersion: 0.3.0
description: Strimzi Kafka Access Operator
home: https://strimzi.io/
icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
keywords:
- kafka
- queue
- stream
- event
- messaging
- datastore
- topic
maintainers:
- email: cncf-strimzi-maintainers@lists.cncf.io
  name: Strimzi Project Maintainers
  url: https://github.com/strimzi/governance
name: strimzi-access-operator
sources:
- https://github.com/strimzi/kafka-access-operator
version: 0.3.0
