# The operator will look up the Kafka instance specified and
# create a secret with the details to connect to the listener specified.
# If no listener is specified it will choose one, preferring an internal listener.
apiVersion: access.strimzi.io/v1alpha1
kind: KafkaAccess
metadata:
  name: my-kafka-access
spec:
  kafka:
    name: my-cluster
    namespace: kafka
    listener: plain
