apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaAccess
metadata:
  name: my-kafka-access
spec:
  kafka:
    name: my-cluster
    namespace: kafka
    listener: tls
  user:
    kind: KafkaUser
    name: my-user
    namespace: kafka
